services:
  - type: web
    name: final-intprog-project-montemar
    env: node
    buildCommand: npm install && npm run render-build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: final-intprog-project-montemar-db
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true 
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1

databases:
  - name: final-intprog-project-montemar-db
    databaseName: management_19lc
    ipAllowList: [] 